@baseUrl = http://localhost:8080


### Create User
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name": "Diego Lima",
    "email": "diegogoncalvesreisdelima21@gmail.com",
    "password": "Password123"
}

### Confirm User
GET {{baseUrl}}/auth/verify-email?token=f2499f1e-346b-41e8-97d5-84b5b3a0295d
Content-Type: application/json


### forgot password
POST {{baseUrl}}/auth/forgot-password
Content-Type: application/json

{
  "email": "diegogoncalvesreisdelima21@gmail.com"
}


### reset password
POST {{baseUrl}}/auth/reset-password/891b439e-ca56-4aff-8ea2-eb37992d93a5
Content-Type: application/json

{
  "code": "620316",
  "password": "Password12345"
}


###  Authenticate
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "diegogoncalvesreisdelima21@gmail.com",
  "password": "Password123"
}


### Refresh Token
POST {{baseUrl}}/auth/refresh
Content-Type: application/json