version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: api_pedidos_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@2025
      POSTGRES_DB: api_pedidos
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
